# Copyright 2026 April Software
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements. See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License. You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.

from __future__ import annotations

import scrapy
from scrapy_playwright.page import PageMethod

from scraper.profiles.cssf_spider.common import save_bytes


class UnOrgHandler:
    org = "un"

    def classify_kind(self, label_text: str, url: str) -> str:
        return "link"

    def start(self, spider, url: str, kind: str) -> scrapy.Request:
        return scrapy.Request(
            url,
            callback=self.handle_html_to_pdf,
            errback=spider.on_link_error,
            cb_kwargs={"spider": spider, "src_url": url, "kind": kind},
            meta={
                "source_url": url,
                "kind": kind,

                "playwright": True,
                "playwright_include_page": True,

                "playwright_context": "un_human",

                "playwright_page_goto_kwargs": {"wait_until": "domcontentloaded", "timeout": 90_000},
                "playwright_page_methods": [
                    PageMethod("wait_for_timeout", 1000),
                ],
            },
            dont_filter=True,
        )

    @staticmethod
    def _looks_like_cloudfront_block(html: str) -> bool:
        t = (html or "").lower()
        return (
            "generated by cloudfront" in t
            or "the request could not be satisfied" in t
            or "request blocked" in t
            or ("cloudfront" in t and "request id" in t)
        )

    async def handle_html_to_pdf(self, response: scrapy.http.Response, spider, src_url: str, kind: str):
        page = response.meta.get("playwright_page")

        try:
            if page is None:
                spider.write_failed(
                    attempted_url=src_url,
                    kind=kind,
                    source_url=src_url,
                    reason=f"HTTP {response.status} (no playwright page)",
                )
                return

            try:
                html = await page.content()
            except Exception as e:
                spider.write_failed(
                    attempted_url=src_url,
                    kind=kind,
                    source_url=src_url,
                    reason=f"Could not read rendered HTML: {type(e).__name__}: {e}",
                )
                return

            if self._looks_like_cloudfront_block(html):
                spider.write_failed(
                    attempted_url=src_url,
                    kind=kind,
                    source_url=src_url,
                    reason="HTTP 403 (CloudFront block page)",
                )
                return

            try:
                await page.evaluate(
                    """() => {
                        const selectors = [
                          '#onetrust-banner-sdk',
                          '.onetrust-pc-dark-filter',
                          '.ot-sdk-container',
                          '.otFloatingRoundedCorner'
                        ];
                        for (const sel of selectors) {
                          const el = document.querySelector(sel);
                          if (el) el.remove();
                        }
                    }"""
                )
            except Exception:
                pass

            if not spider._inc_and_check_limit():
                return

            pdf_bytes: bytes = await page.pdf(
                format="A4",
                print_background=True,
                prefer_css_page_size=True,
                margin={"top": "12mm", "bottom": "12mm", "left": "10mm", "right": "10mm"},
            )

            fp = save_bytes(
                spider.out_dir,
                seq=spider.count,
                url=src_url,
                body=pdf_bytes,
                ext="pdf",
            )
            yield {"saved_path": str(fp), "source_url": src_url, "url": response.url}

        except Exception as e:
            spider.write_failed(
                attempted_url=src_url,
                kind=kind,
                source_url=src_url,
                reason=f"UN HTML->PDF failed: {type(e).__name__}: {e}",
            )
        finally:
            if page is not None:
                try:
                    await page.close()
                except Exception:
                    pass
